### NUMPY

In [1]:
#Importing Numpy
import numpy as np

In [2]:
#making a numpy array and printing it
arr = np.array([1,2,3,4])
print(arr)

[1 2 3 4]


In [3]:
#Multidimensional Array
arr=np.array([[1,2,3,4],
            [5,6,7,8]])
print(arr)
print(arr[1][2])
print(arr[1,2])
#to get dimension of arr
#print(arr.ndim)
#to get length breadth height
#print(arr.shape)

[[1 2 3 4]
 [5 6 7 8]]
7
7


In [4]:
#filtering = refers to the process of selecting elements 
#            from an array that match a given condition

ages = np.array([[21,17,18,20,16,30,18,65],
                [39,22,15,99,18,19,20,21]])

# teenagers = ages[ages<18]
# adults=ages[(ages>=18) & (ages<65)]
# seniors=ages[ages>=65]
# evens=ages[ages%2==0]
# odds=ages[ages%2!=0]
# print(teenagers)

#just replaces ages<18 with 0
adults=np.where(ages>=18, ages, 0)

In [5]:
#scalar arithmetic

arr=np.array([1,2,3])
#operations apply to each element
print(arr+1)
print(arr*2)
print(arr-2)
print(arr/2)
print(arr**2)

#vectorized math functions

array=np.array([1,2,3])

print(np.sqrt(array))
#to round off np.round(array)
#np.pi gives pi
#np.ceil ceils the digits
#print(np.pi*array**2)

#element wise arithmetic

array1=np.array([1,2,3])
array2=np.array([4,5,6])

print(array1 + array2)

#comparison operator

score = np.array([55,100,58,60,85])
#gives boolean answers 
print(score==100)
print(score>=60)

score[score<70]=0
print(score)

[2 3 4]
[2 4 6]
[-1  0  1]
[0.5 1.  1.5]
[1 4 9]
[1.         1.41421356 1.73205081]
[5 7 9]
[False  True False False False]
[False  True False  True  True]
[  0 100   0   0  85]


In [6]:
arr=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]])
#array[start:end:step]
print(arr[0:3:2])
#print column
print(arr[:,0])
#i love this!!!
print(arr[:,0:3:2])
print(arr[0:2,0:2])

[[ 1  2  3  4]
 [ 9 10 11 12]]
[ 1  5  9 13]
[[ 1  3]
 [ 5  7]
 [ 9 11]
 [13 15]]
[[1 2]
 [5 6]]


In [7]:
#seed is to get same results can be neglected
rng = np.random.default_rng(seed=1)
#not necessary to write low high size
print(rng.integers(low=1,high=7,size=(3,2)))

#to get random floating integer
#print(np.random.uniform(low=-1,high=1,size=3))

array=np.array([1,2,3,4,5])
rng.shuffle(array)
choice=rng.choice(array, size=2)
print(array)
print(choice)

[[3 4]
 [5 6]
 [1 1]]
[4 1 2 5 3]
[3 2]


In [9]:
#aggregate functions = summarize data and typically returns a single value

array = np.array([[1,2,3,4],[5,6,7,8]])

#print(np.sum(array))
#print(np.mean(array))
#print(np.std(array)) standard deviation
#print(np.var(array)) variance
#print(np.min(array)) 
#print(np.max(array))
#print(np.argmin(array)) position of min value
#print(np.argmax(array))

#to get all columns sum axis = 0 
#for row axis = 1 
print(np.sum(array, axis=0))
print(np.sum(array, axis=1))

[ 6  8 10 12]
[10 26]


In [10]:
#broadcasting allows numpy to perform operations on arrays 
#with different shapes by virtually expanding dimensions
#so they match the larger array's shape

#the dimensions have the same size
#OR
#one of the dimensions has a size of 1

# (1,4) and (4,1) works
array1=np.array([[1,2,3,4]])
array2=np.array([[1],[2],[3],[4]])
print(array1*array2)

# (4,4) and (4,1) works
# array1=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]])
# array2=np.array([[1],[2],[3],[4]])
# print(array1*array2)

# (4,4) and (4,4) works 
# array1 = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]])
# array2 = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]])
# print(array1*array2)

#all except these cases dont work 

[[ 1  2  3  4]
 [ 2  4  6  8]
 [ 3  6  9 12]
 [ 4  8 12 16]]


In [11]:
# np.corrcoef(x, y)[0,1] — computes the correlation (−1 to +1) between two arrays
# np.polyfit(x, y, 1) — finds the best-fit straight line (slope + intercept)
# np.sort(x) — sorts an array in ascending order
# .values — extracts the raw NumPy array from a Pandas Series